// import { Auth } from '@auth/core'
// import type { AuthAction, Session } from '@auth/core/types'
// import type { APIContext } from 'astro'
// import { parseString } from 'set-cookie-parser'
// import authConfig from 'auth:config'